const ADD_COORDINATE_DATA = 'most-used-words/ADD_COORDINATE_DATA';

const AUTO_SELECT = 'most-used-words/AUTO_SELECT';
const START_AUTO_SELECT = 'most-used-words/START_AUTO_SELECT';
const STOP_AUTO_SELECT = 'most-used-words/STOP_AUTO_SELECT';

const ON_SELECT = 'most-used-words/ON_SELECT';

const SET_ONSELECT_INDEX = 'most-used-words/SET_ONSELECT_INDEX';

const RENDER_SPIRAL_LINE = 'most-used-words/RENDER_SPIRAL_LINE';
const RENDER_SPIRAL_POINTS = 'most-used-words/RENDER_SPIRAL_POINTS';

const ON_HELPER_CLICK = 'most-used-words/ON_HELPER_CLICK';

const SHOW_CHART = 'most-used-words/SHOW_CHART';

const SET_SECTION_POSITION = 'most-used-words/SET_SECTION_POSITION';

export default {
  ADD_COORDINATE_DATA,
  AUTO_SELECT,
  ON_SELECT,
  SET_ONSELECT_INDEX,
  START_AUTO_SELECT,
  STOP_AUTO_SELECT,
  RENDER_SPIRAL_LINE,
  RENDER_SPIRAL_POINTS,
  ON_HELPER_CLICK,
  SHOW_CHART,
  SET_SECTION_POSITION
};
